name: flutter_apps_dashboard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  path_provider: ^2.1.3
  syncfusion_flutter_pdfviewer: ^25.2.7
  cupertino_icons: ^1.0.6
  html: any
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/resume.pdf

  uses-material-design: true
